export const GAME_CONFIG = {
  MIN_NUMBER: 1,
  MAX_NUMBER: 9,
  LENGTH: 3,
};

export const GAME_RESULT_STATE = {
  CORRECT: "CORRECT",
  PARTIAL_CORRECT: "PARTIAL_CORRECT",
  NOTHING: "NOTHING",
};
